# Generated by Django 4.2 on 2024-01-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_numer',
            field=models.CharField(max_length=20),
        ),
    ]
