# Generated by Django 4.2 on 2024-01-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_phone_numer_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=911111111, max_length=20),
            preserve_default=False,
        ),
    ]
