# Generated by Django 4.2 on 2024-01-10 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_alter_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lat', models.CharField(max_length=50)),
                ('origin_long', models.CharField(max_length=50)),
                ('destination_lat', models.CharField(max_length=50)),
                ('destination_long', models.CharField(max_length=50)),
                ('cost', models.PositiveIntegerField()),
                ('duration', models.TimeField()),
                ('status', models.CharField(choices=[('0', 'initial'), ('1', 'confirmed'), ('2', 'driver accepted'), ('3', 'driver arrived to origin'), ('4', 'delivered'), ('-1', 'canceled from user'), ('-2', 'canceled from driver')], default='0', max_length=20)),
                ('description', models.TextField(null=True)),
                ('has_return', models.BooleanField(default=False)),
                ('payment', models.CharField(choices=[('0', 'not paid'), ('1', 'online paid')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
