# Generated by Django 4.2 on 2024-01-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order_customer_alter_order_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='destination_lat',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='origin_lat',
            new_name='origin',
        ),
        migrations.RemoveField(
            model_name='order',
            name='destination_long',
        ),
        migrations.RemoveField(
            model_name='order',
            name='origin_long',
        ),
    ]
