# Generated by Django 4.2 on 2024-01-10 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_destination_lat_order_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='posting_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
