# Generated by Django 4.2 on 2024-01-10 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_order_posting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='posting_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
