# Generated by Django 4.2 on 2024-01-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiKey',
        ),
    ]
